on:
  pull_request:
name: gradle harness test
jobs:
  ubuntu:
    services:
      emulator:
        image: gcr.io/cloud-spanner-emulator/emulator:latest
        ports:
          - 9010:9010
          - 9020:9020
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        java: [11, 17]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: zulu
          java-version: ${{matrix.java}}
      - run: java -version
      - run: ./gradlew clean liquibaseHarnessTest
      - run: ./gradlew clean build